FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src
COPY . .

RUN dotnet tool restore
RUN dotnet restore Tournament.API/Tournament.API.csproj

CMD ["dotnet", "tool", "run", "dotnet-ef", "database", "update", "--project", "Tournament.Infrastructure", "--startup-project", "Tournament.API"]
